"""R-W3-RATCHET-1 (w3c-0 design closure §13.2): the correction failure-ratchet.

Stdlib verifier for ``contracts/correction_baseline.json``. The ledger is the
exact failing/erroring set of the focused 17-module correction command at a
slice landing; across the w3-correction branch it may only SHRINK. This module
holds the mechanics AND the trusted runner that makes them binding; the contract
test ``tests/contracts/test_correction_ratchet.py`` exercises them hostilely.

A *failure unit* is the COMPLETE typed identity of one red thing:

  * ``("ordinary", test_id, fingerprint)`` — one fingerprint of a failing row;
  * ``("loader", module, fingerprint, unmask_rule)`` — one loader (import) mask,
    identity INCLUDING its unmask rule, so weakening the rule is a new unit;
  * ``("setupclass", cls, fingerprint, unmask_rule)`` — one ``setUpClass`` mask,
    likewise carrying its unmask rule.

Because the mask identity carries ``unmask_rule``, editing a mask's rule turns it
into a unit the parent never had — a subset check reddens rather than silently
accepting a loosened mask.

Totals semantics (§13.2, r13)
-----------------------------
``totals.unique_test_ids`` is the count of unique OBSERVED ids, which is one per
ordinary failing row PLUS one per loader mask PLUS one per ``setUpClass`` mask
(each mask is a real ``_FailedTest`` / ``setUpClass`` observation in the run).
For the slice-0 seed that is ``7 ordinary + 9 loader + 0 setupclass = 16`` — NOT
``len(failing)``. ``failures`` counts ``kind == "failure"`` rows; ``errors``
counts ``kind == "error"`` rows plus every loader and ``setUpClass`` mask.
:func:`_derived_totals` recomputes all three so a hand-edited total reddens.

Atomic-member fingerprints for the seven structural ids (§13.2)
---------------------------------------------------------------
For the aggregate structural assertions (``test_structural_layout`` /
``test_tests_layout_contract``) the fingerprint is NOT the truncated terminal
exception line — it is the sorted set of atomic ``category|side|member``
violations recomputed from the LIVE declared-versus-actual collections by the
closed seven-id map :data:`STRUCTURAL_EXTRACTOR_IDS` / :func:`structural_atoms`.
Adding or removing one declared home changes exactly one atom, so the add-only
subset check bites at member granularity; a mapped test that fails but yields no
atom falls back to the exception line, which is unledgered and therefore reddens.

Trusted runner — the honesty boundary (§13.2)
---------------------------------------------
The three ``verify_*`` functions are PURE dict functions: given a hand-built
``observed`` set they will bless it, so they are NOT the trust boundary on their
own. The binding entry point is :func:`run_and_verify`, which (1) RUNS the exact
pinned command from the ledger as a subprocess in the clean worktree, (2)
validates the run is honest — a ``Ran N`` summary with ``N > 0``, a terminal
``OK``/``FAILED`` status, a return code consistent with that status, that every
named module was DISCOVERED (executed at least one test or is a declared loader
mask — a deleted or unmask-to-zero-tests module is rejected, never silent
progress), and that every observed identity is fully qualified — (3) derives
``observed`` from that real output (never hand-assembled), rewriting the seven
structural ids to their atomic members, (4) loads the PARENT ledger via
``git show <base_ref>:contracts/correction_baseline.json`` (the caller cannot
substitute a parent), and (5) invokes
:func:`verify_observation_projection`, :func:`verify_subset_of_parent` and
:func:`verify_frozen_structure` INSEPARABLY — all three or it fails.

Seed regeneration (r14 slice-1 deliverable)
-------------------------------------------
The on-disk ``contracts/correction_baseline.json`` committed at slice 0 is a
best-effort SEED and is deliberately NOT edited by this slice (it is outside the
ratchet-hardening allowed paths). It is known-stale against the semantics above:
its loader ``module`` keys are bare basenames rather than fully qualified, its
seven structural ``fingerprints`` are truncated terminal lines rather than atomic
members, its ``totals.unique_test_ids`` is ``len(failing)`` (7) rather than 16,
and it carries an extra ``ratchet_status`` annotation key. At slice-1 landing the
CONDUCTOR regenerates the seed in the clean context using the fully-qualified
loader parser (:func:`observe_from_unittest_output`) and the atomic extractor
(:func:`structural_atoms`) provided here; this module + test supply the extractor
and runner, not the regenerated bytes.
"""

from __future__ import annotations

import json
import re
import shlex
import subprocess
from collections import namedtuple
from pathlib import Path


class RatchetViolation(Exception):
    """Raised when a ledger breaks the shrink-only correction ratchet law."""


class RatchetRunError(RatchetViolation):
    """A dishonest or unusable RUN — zero discovery, tampered summary, bad
    return code, an undiscovered module, or an unretrievable parent ledger.

    Subclasses :class:`RatchetViolation` so callers that guard the ratchet with
    ``except RatchetViolation`` fail closed on a dishonest run as well.
    """


class ExtractorUnavailable(Exception):
    """The live declared-versus-actual collections for a structural id could not
    be recomputed (missing layout data / unimportable contract). The runner
    treats this as "no atom" and keeps the terminal line, which then reddens."""


# --------------------------------------------------------------------------- #
# JSON loading — duplicate keys are corruption, never tolerated
# --------------------------------------------------------------------------- #

def _reject_duplicate_keys(pairs):
    """``object_pairs_hook`` that refuses any duplicate key in a JSON object.

    A duplicate key is silent data loss under the default ``dict`` behaviour, so
    it is treated as a corrupt ledger rather than tolerated. The hook fires for
    every object in the document, so nested duplicates are rejected too.
    """
    obj: dict = {}
    for key, value in pairs:
        if key in obj:
            raise RatchetViolation(f"duplicate key in ledger JSON: {key!r}")
        obj[key] = value
    return obj


def _loads_no_dupes(text):
    """``json.loads`` that raises :class:`RatchetViolation` on ANY duplicate key.

    The single JSON entry point for this module; :func:`load_ledger` uses it so
    that a duplicated object key — at any nesting depth — is caught before the
    lossy ``dict`` collapse can hide a forged or corrupted ledger.
    """
    return json.loads(text, object_pairs_hook=_reject_duplicate_keys)


def load_ledger(path):
    """Parse the correction ledger, rejecting duplicate object keys (nested too).

    The parsed dict is returned verbatim; no normalisation or defaulting is done
    so that shape assertions see the ledger exactly as written on disk.
    """
    with open(Path(path), "r", encoding="utf-8") as handle:
        return _loads_no_dupes(handle.read())


def _sorted(items):
    """Deterministic, crash-proof ordering for tuples in error messages."""
    return sorted(items, key=str)


# --------------------------------------------------------------------------- #
# Failure units — COMPLETE typed identities
# --------------------------------------------------------------------------- #

def _ordinary_units(ledger):
    """``{("ordinary", id, fp)}`` over every fingerprint of every failing row."""
    return {
        ("ordinary", row["id"], fp)
        for row in ledger.get("failing", [])
        for fp in row.get("fingerprints", [])
    }


def _loader_units(ledger):
    """``{("loader", module, fp, unmask_rule)}`` — full loader-mask identities."""
    return {
        ("loader", m["module"], m["fingerprint"], m["unmask_rule"])
        for m in ledger.get("loader_masks", [])
    }


def _setupclass_units(ledger):
    """``{("setupclass", cls, fp, unmask_rule)}`` — full setUpClass-mask ids."""
    return {
        ("setupclass", m["class"], m["fingerprint"], m["unmask_rule"])
        for m in ledger.get("setupclass_masks", [])
    }


def failure_units(ledger):
    """The complete set of typed failure-unit tuples for ``ledger``.

    Ordinary ``("ordinary", id, fp)`` triples plus loader and ``setUpClass`` mask
    identities as ``("loader"/"setupclass", name, fp, unmask_rule)`` 4-tuples.
    The kind tag keeps the three namespaces from colliding; the trailing
    ``unmask_rule`` makes a rule edit a genuinely different unit.
    """
    return _ordinary_units(ledger) | _loader_units(ledger) | _setupclass_units(ledger)


# --------------------------------------------------------------------------- #
# Observation parsing — the ONLY sanctioned source of an observed set
# --------------------------------------------------------------------------- #

_HEADER_RE = re.compile(r"^(?:FAIL|ERROR):\s+(\S+)\s+\((.+)\)\s*$")
_SEPARATOR_RE = re.compile(r"^(?:=+|-+)\s*$")
_SUMMARY_RE = re.compile(r"^Ran\s+\d+\s+tests?\b")
_LOADER_PREFIX = "unittest.loader._FailedTest"
_FAILED_IMPORT_RE = re.compile(r"Failed to import test module:\s*(\S+)")
_NO_MODULE_RE = re.compile(r"No module named ['\"]([^'\"]+)['\"]")


def _loader_module_identity(lines, start, end, header_method, suffix):
    """FULLY-QUALIFIED module identity for one ``_FailedTest`` block.

    unittest renders the ``_FailedTest`` header with only the module's LAST
    component (``definitely_missing_module``), so keying off the header basename
    is ambiguous — two ``pkg.a.same`` / ``pkg.b.same`` modules would collide
    (§13.2 fully-qualified requirement; the r2 basename finding). The dotted
    identity is recovered from the block body instead:

      * ``Failed to import test module: <name>`` — unittest emits the FQ dotted
        name here for a module that EXISTS but fails to import; for a genuinely
        MISSING module it degrades to the bare basename;
      * ``ModuleNotFoundError: No module named '<dotted>'`` — carries the FQ
        module for the missing-module case.

    The fully-qualified candidate wins: the import line when it is already
    dotted, else the ``No module named`` dotted name, else the bare import line,
    else the 3.11+ header suffix, else the bare header method.
    """
    failed_import = None
    no_module = None
    for j in range(start + 1, end):
        line = lines[j]
        if _SUMMARY_RE.match(line):
            break
        if failed_import is None:
            hit = _FAILED_IMPORT_RE.search(line)
            if hit:
                failed_import = hit.group(1)
        hit = _NO_MODULE_RE.search(line)
        if hit:
            no_module = hit.group(1)
    if failed_import and "." in failed_import:
        return failed_import
    if no_module:
        return no_module
    if failed_import:
        return failed_import
    return suffix if suffix else header_method


def observe_from_unittest_output(text):
    """Parse real ``python -m unittest -v`` / ``discover`` output into an
    observed failure set.

    Returns ``{"ordinary": set[(id, fp)], "loader": set[(module, fp)],
    "setupclass": set[(cls, fp)]}``.

    Each ``FAIL:``/``ERROR:`` detail block contributes one observation:

      * an ordinary block ``FAIL: test_x (pkg.mod.Case)`` plus its final
        exception line becomes ``("pkg.mod.Case::test_x", "<exception line>")``;
      * an ``ERROR`` whose class path is ``unittest.loader._FailedTest[.<module>]``
        becomes a loader observation keyed by the FULLY-QUALIFIED module name
        recovered from the block body (:func:`_loader_module_identity`), never the
        ambiguous header basename, so ``u[0]`` is the dotted module;
      * an ``ERROR: setUpClass (pkg.mod.Case)`` becomes a setUpClass observation
        keyed by the class path.

    The unmask rule is a ledger-side policy annotation, not something a test run
    emits, so loader/setUpClass observations carry only ``(name, fingerprint)``.
    :func:`verify_observation_projection` matches masks on that pair; the rule
    itself is frozen by :func:`verify_subset_of_parent` /
    :func:`verify_frozen_structure`.

    This function exists so callers derive ``observed`` from a REAL run instead
    of hand-forging it (see the module docstring's honesty note).
    """
    lines = text.splitlines()
    header_idx = [i for i, ln in enumerate(lines) if _HEADER_RE.match(ln)]

    ordinary: set = set()
    loader: set = set()
    setupclass: set = set()

    for pos, start in enumerate(header_idx):
        match = _HEADER_RE.match(lines[start])
        method, class_path = match.group(1), match.group(2)

        # The block body runs until the next detail header (blocks are also
        # bounded by the trailing "Ran N tests" summary or end of text). The
        # fingerprint is the block's last non-blank, non-separator line — i.e.
        # the terminal exception line, skipping the "===="/"----" rules unittest
        # draws around each block.
        end = header_idx[pos + 1] if pos + 1 < len(header_idx) else len(lines)
        fingerprint = None
        for j in range(start + 1, end):
            line = lines[j]
            if _SUMMARY_RE.match(line):
                break
            if line.strip() == "" or _SEPARATOR_RE.match(line):
                continue
            fingerprint = line.rstrip()
        if fingerprint is None:
            continue

        if class_path == _LOADER_PREFIX or class_path.startswith(_LOADER_PREFIX + "."):
            suffix = class_path[len(_LOADER_PREFIX):].lstrip(".")
            module = _loader_module_identity(lines, start, end, method, suffix)
            loader.add((module, fingerprint))
        elif method == "setUpClass" or method.startswith("setUpClass"):
            setupclass.add((class_path, fingerprint))
        else:
            # Normalise the Python 3.11+ "(pkg.mod.Case.test_x)" form (method
            # duplicated inside the parens) back to the bare class path.
            if class_path.endswith("." + method):
                class_path = class_path[: -(len(method) + 1)]
            ordinary.add((f"{class_path}::{method}", fingerprint))

    return {"ordinary": ordinary, "loader": loader, "setupclass": setupclass}


# --------------------------------------------------------------------------- #
# Observation projection — ledger is the exact bidirectional image of a run
# --------------------------------------------------------------------------- #

def _pair(observed_tuple):
    """Normalise an observed tuple to its ``(name, fingerprint)`` match key.

    Ordinary observations are already ``(id, fp)``; loader/setUpClass tuples may
    carry a trailing ``unmask_rule`` (when assembled from the ledger) which is
    not part of the observation identity and is dropped here.
    """
    return (observed_tuple[0], observed_tuple[1])


def _ordinary_ledger_pairs(ledger):
    return [
        (row["id"], fp)
        for row in ledger.get("failing", [])
        for fp in row.get("fingerprints", [])
    ]


def _loader_ledger_pairs(ledger):
    return [(m["module"], m["fingerprint"]) for m in ledger.get("loader_masks", [])]


def _setupclass_ledger_pairs(ledger):
    return [(m["class"], m["fingerprint"]) for m in ledger.get("setupclass_masks", [])]


def _dedupe_or_raise(kind, pairs):
    """Collapse ``pairs`` to a set, but raise if a duplicate would be hidden.

    A duplicated ledger row or mask must not silently vanish into set
    membership; multiplicity is checked here so the projection stays honest.
    """
    seen: set = set()
    for pair in pairs:
        if pair in seen:
            raise RatchetViolation(
                f"{kind}: duplicate ledger entry would silently collapse: {pair!r}"
            )
        seen.add(pair)
    return seen


def verify_observation_projection(ledger, observed):
    """Assert the ledger is the EXACT bidirectional projection of ``observed``.

    ``observed`` is ``{"ordinary": set[(id, fp)], "loader": set[(module, fp)],
    "setupclass": set[(cls, fp)]}`` (mask tuples may carry a trailing
    ``unmask_rule`` which is ignored for matching). For each of the three
    namespaces every ledger entry must be observed AND every observed entry must
    be in the ledger. Any asymmetry — a masked module that unmasks to a red test
    outside the ledger, a ledgered failure that no longer reproduces, a stale
    mask — raises :class:`RatchetViolation`. A duplicated ledger row or mask
    raises rather than collapsing.

    ``observed`` MUST be produced by :func:`observe_from_unittest_output` from a
    real run; passing a hand-built set defeats the whole defense.
    """
    checks = (
        ("ordinary", _ordinary_ledger_pairs(ledger), observed.get("ordinary", ())),
        ("loader", _loader_ledger_pairs(ledger), observed.get("loader", ())),
        ("setupclass", _setupclass_ledger_pairs(ledger), observed.get("setupclass", ())),
    )
    problems = []
    for kind, ledger_pairs, observed_tuples in checks:
        ledgered = _dedupe_or_raise(kind, ledger_pairs)
        seen = {_pair(t) for t in observed_tuples}
        unobserved = ledgered - seen
        unledgered = seen - ledgered
        if unobserved:
            problems.append(f"{kind}: ledger entries not observed: {_sorted(unobserved)}")
        if unledgered:
            problems.append(f"{kind}: observed entries absent from ledger: {_sorted(unledgered)}")
    if problems:
        raise RatchetViolation("observation projection mismatch; " + "; ".join(problems))


# --------------------------------------------------------------------------- #
# Subset law — the child's failure units may only shrink
# --------------------------------------------------------------------------- #

def verify_subset_of_parent(child_ledger, parent_ledger):
    """Assert child failure units are a subset of the parent's; classify shrink.

    Units are the COMPLETE identities from :func:`failure_units`, so a loosened
    ``unmask_rule`` is a child unit absent from the parent. Returns
    ``"unchanged"`` when the unit sets are identical and ``"shrunk"`` when the
    child is a strict subset. Any child unit not present in the parent — a new
    failure or an edited mask — raises :class:`RatchetViolation`.
    """
    child = failure_units(child_ledger)
    parent = failure_units(parent_ledger)
    added = child - parent
    if added:
        raise RatchetViolation(
            "child failure units are not a subset of the parent; "
            f"units added: {_sorted(added)}"
        )
    return "unchanged" if child == parent else "shrunk"


# --------------------------------------------------------------------------- #
# Frozen structure — everything except a shrink is immutable
# --------------------------------------------------------------------------- #

_SCALAR_FROZEN_KEYS = (
    "contract_id", "schema_version", "purpose",
    "observed_utc", "command", "measurement_context",
)
_ROW_KEYS = frozenset({"id", "kind", "fingerprint_mode", "subtest_vectors", "fingerprints"})
_LOADER_KEYS = frozenset({"module", "fingerprint", "unmask_rule"})
_SETUPCLASS_KEYS = frozenset({"class", "fingerprint", "unmask_rule"})
_TOTALS_KEYS = frozenset({"failures", "errors", "unique_test_ids"})


def _derived_totals(ledger):
    """Recompute ``totals`` from live rows and masks (never free-edited).

    ``failures`` counts ``kind == "failure"`` rows; ``errors`` counts
    ``kind == "error"`` rows PLUS every loader and ``setUpClass`` mask (each
    masked import/class error is an erroring unit); ``unique_test_ids`` is the
    count of unique OBSERVED ids — one per failing row PLUS one per loader mask
    PLUS one per ``setUpClass`` mask (each mask is a real ``_FailedTest`` /
    ``setUpClass`` observation in the run), i.e. ``16`` for the slice-0 seed
    (``7 + 9 + 0``), NOT ``len(failing)`` (§13.2 r13).
    """
    rows = ledger.get("failing", [])
    loader = ledger.get("loader_masks", [])
    setupclass = ledger.get("setupclass_masks", [])
    failures = sum(1 for r in rows if r.get("kind") == "failure")
    errors = (
        sum(1 for r in rows if r.get("kind") == "error")
        + len(loader)
        + len(setupclass)
    )
    unique_test_ids = len(rows) + len(loader) + len(setupclass)
    return {"failures": failures, "errors": errors, "unique_test_ids": unique_test_ids}


def _check_masks(field, keyset, name_key, child_ledger, parent_ledger):
    """Freeze a mask list: key sets fixed, no duplicates, only removals."""
    problems = []
    child_masks = child_ledger.get(field, [])
    parent_masks = parent_ledger.get(field, [])

    for mask in child_masks:
        if set(mask) != keyset:
            problems.append(
                f"{field} key set changed for {mask.get(name_key)!r} "
                f"(is {_sorted(set(mask))}, must be {_sorted(keyset)})"
            )

    seen: set = set()
    for mask in child_masks:
        identity = (mask.get(name_key), mask.get("fingerprint"), mask.get("unmask_rule"))
        if identity in seen:
            problems.append(f"duplicate {field}: {identity!r}")
        seen.add(identity)

    parent_identities = {
        (m.get(name_key), m.get("fingerprint"), m.get("unmask_rule")) for m in parent_masks
    }
    added = seen - parent_identities
    if added:
        problems.append(f"{field} added (only removal allowed): {_sorted(added)}")
    return problems


def verify_frozen_structure(child_ledger, parent_ledger):
    """Assert every non-removal structural invariant is frozen vs the parent.

    Removals (fewer rows, masks, or fingerprints) are the only permitted change.
    Any of the following raises :class:`RatchetViolation`:

      * the top-level key SET differs (a key was added, removed, or renamed);
      * any frozen top-level scalar changed — ``contract_id``, ``schema_version``,
        ``purpose``, ``observed_utc``, ``command``, or ``measurement_context``;
      * ``totals`` is not a dict with exactly ``{failures, errors,
        unique_test_ids}``, or any of those disagrees with the value DERIVED from
        the rows and masks (a forged ``unique_test_ids`` or a mis-counted total,
        including one that ignores ``setUpClass`` masks, is caught here);
      * a duplicate failing ``id`` or a duplicate mask;
      * a failing row whose key set is not exactly
        ``{id, kind, fingerprint_mode, subtest_vectors, fingerprints}``, or whose
        ``fingerprints`` list is empty;
      * a surviving id whose ``kind`` or ``fingerprint_mode`` changed, whose
        ``subtest_vectors`` INCREASED, or which gained a fingerprint;
      * a failing id or a loader/``setUpClass`` mask ADDED versus the parent, or a
        mask whose key set changed.

    Returns ``"frozen"`` when the child is a clean shrink of / identical to the
    parent.
    """
    problems = []

    # -- top-level key set frozen -------------------------------------------- #
    child_keys, parent_keys = set(child_ledger), set(parent_ledger)
    if child_keys != parent_keys:
        problems.append(
            f"top-level key set changed (added={_sorted(child_keys - parent_keys)}, "
            f"removed={_sorted(parent_keys - child_keys)})"
        )

    # -- frozen top-level scalar values -------------------------------------- #
    for key in _SCALAR_FROZEN_KEYS:
        if child_ledger.get(key) != parent_ledger.get(key):
            problems.append(f"top-level value changed: {key!r}")

    # -- failing rows: self-contained shape checks --------------------------- #
    child_rows_list = child_ledger.get("failing", [])
    ids = [r.get("id") for r in child_rows_list]
    if len(ids) != len(set(ids)):
        dups = _sorted({i for i in ids if ids.count(i) > 1})
        problems.append(f"duplicate failing id(s): {dups}")
    for row in child_rows_list:
        if set(row) != _ROW_KEYS:
            problems.append(
                f"failing row key set changed for {row.get('id')!r} "
                f"(is {_sorted(set(row))}, must be {_sorted(_ROW_KEYS)})"
            )
        if not row.get("fingerprints"):
            problems.append(f"empty fingerprints for row {row.get('id')!r}")

    # -- failing rows: parent-relative (only-shrink) checks ------------------ #
    parent_rows = {r["id"]: r for r in parent_ledger.get("failing", [])}
    child_rows: dict = {}
    for r in child_rows_list:
        child_rows.setdefault(r.get("id"), r)  # first wins; any dup already flagged

    new_ids = set(child_rows) - set(parent_rows)
    if new_ids:
        problems.append(f"failing rows added (only removal allowed): {_sorted(new_ids)}")

    for tid in set(child_rows) & set(parent_rows):
        child_row, parent_row = child_rows[tid], parent_rows[tid]
        if child_row.get("kind") != parent_row.get("kind"):
            problems.append(f"kind changed for {tid!r}")
        if child_row.get("fingerprint_mode") != parent_row.get("fingerprint_mode"):
            problems.append(f"fingerprint_mode changed for {tid!r}")
        if child_row.get("subtest_vectors", 0) > parent_row.get("subtest_vectors", 0):
            problems.append(f"subtest_vectors increased for {tid!r}")
        added_fps = set(child_row.get("fingerprints", ())) - set(parent_row.get("fingerprints", ()))
        if added_fps:
            problems.append(f"fingerprints added for {tid!r}: {_sorted(added_fps)}")

    # -- masks: key sets frozen, no duplicates, only removals ---------------- #
    problems += _check_masks("loader_masks", _LOADER_KEYS, "module", child_ledger, parent_ledger)
    problems += _check_masks("setupclass_masks", _SETUPCLASS_KEYS, "class", child_ledger, parent_ledger)

    # -- totals fully derived and checked ------------------------------------ #
    totals = child_ledger.get("totals")
    if not isinstance(totals, dict) or set(totals) != _TOTALS_KEYS:
        shown = _sorted(set(totals)) if isinstance(totals, dict) else totals
        problems.append(f"totals key set changed (is {shown}, must be {_sorted(_TOTALS_KEYS)})")
        totals = totals if isinstance(totals, dict) else {}
    derived = _derived_totals(child_ledger)
    for key in ("failures", "errors", "unique_test_ids"):
        if totals.get(key) != derived[key]:
            problems.append(f"totals.{key}={totals.get(key)} != derived {derived[key]}")

    if problems:
        raise RatchetViolation("frozen-structure violation; " + "; ".join(problems))
    return "frozen"


# --------------------------------------------------------------------------- #
# Atomic-member extractor — the closed seven-id map (§13.2)
#
# For the aggregate structural assertions the ledger fingerprint is the sorted
# set of atomic ``category|side|member`` violations, recomputed HERE from the
# LIVE declared-versus-actual collections (``contracts/repo_layout.json`` +
# disk + the tests-layout contract), never the truncated terminal exception
# line. Adding/removing one declared home flips exactly one atom, so the
# add-only subset check bites at member granularity.
# --------------------------------------------------------------------------- #

_ENUMERATED = ("source_layout", "test_layout")
_SL_ID = "tests.contracts.test_structural_layout.StructuralLayoutContract"
_TL_ID = "tests.contracts.test_tests_layout_contract.TestsLayoutContract"


def symmetric_atoms(category, left_label, left, right_label, right):
    """Atoms for a two-set parity: ``category|left_label|m`` for each member only
    on the left, ``category|right_label|m`` for each member only on the right."""
    left, right = set(left), set(right)
    return (
        {f"{category}|{left_label}|{m}" for m in left - right}
        | {f"{category}|{right_label}|{m}" for m in right - left}
    )


def _discover_repo_root():
    for parent in Path(__file__).resolve().parents:
        if (parent / "scripts").is_dir() and (parent / "tests").is_dir():
            return parent
    raise ExtractorUnavailable("repo root (a dir holding both scripts/ and tests/) not found")


def _load_structural_sections(root):
    """The live ``structural_layout`` block (dup-key-safe load, same data the
    structural-layout guard reads)."""
    path = root / "contracts" / "repo_layout.json"
    return _loads_no_dupes(path.read_text(encoding="utf-8"))["structural_layout"]


def _sl_declared_homes(section):
    """Declared home path per governed file (mirrors the structural guard):
    root-allowlisted files keep their basename; group members live at
    ``<target_dir>/<member>`` when ``placement_enforced`` else flat."""
    enforced = bool(section.get("placement_enforced", False))
    homes = set(section.get("root_allowlist", []))
    for group in section.get("groups", []):
        for member in group["members"]:
            homes.add(f"{group['target_dir']}/{member}" if enforced else member)
    return homes


def _sl_actual_files(section, root):
    """On-disk governed files under a section root, home-relative (data dirs and
    subpackage ``__init__.py`` markers excluded, exactly as the guard does)."""
    section_root = root / section["root"]
    data_dirs = set(section.get("data_dirs", []))
    out = set()
    for path in section_root.glob(section["glob"]):
        if not path.is_file():
            continue
        rel = path.relative_to(section_root)
        if rel.parts and rel.parts[0] in data_dirs:
            continue
        if path.name == "__init__.py" and len(rel.parts) > 1:
            continue
        out.add(rel.as_posix())
    return out


def _sl_declared_basenames(section):
    declared = set(section.get("root_allowlist", []))
    for group in section.get("groups", []):
        declared.update(group["members"])
    return declared


def _extract_parity(root, section_name):
    section = _load_structural_sections(root)[section_name]
    declared = _sl_declared_homes(section)
    actual = _sl_actual_files(section, root)
    return symmetric_atoms(section_name, "missing", declared, "undeclared", actual)


def _extract_src_home(root):
    return _extract_parity(root, "source_layout")


def _extract_test_home(root):
    return _extract_parity(root, "test_layout")


def _extract_guard(root):
    # The negative control's live assertion is the same source_layout parity
    # ("the real cover must be green now").
    return _extract_parity(root, "source_layout")


def _extract_phantom(root):
    struct = _load_structural_sections(root)
    atoms = set()
    for name in _ENUMERATED:
        section = struct[name]
        section_root = root / section["root"]
        homes = [{"target_dir": "."}] + section.get("groups", [])
        for member in _sl_declared_basenames(section):
            found = any(
                (section_root / member).exists()
                or (section_root / g["target_dir"] / member).exists()
                for g in homes
            )
            if not found:
                atoms.add(f"{name}|phantom|{member}")
    return atoms


def _extract_placement(root):
    struct = _load_structural_sections(root)
    atoms = set()
    for name in _ENUMERATED:
        section = struct[name]
        section_root = root / section["root"]
        enforced = section["placement_enforced"]
        for group in section.get("groups", []):
            for member in group["members"]:
                home = (
                    section_root / group["target_dir"] / member
                    if enforced
                    else section_root / member
                )
                if not home.is_file():
                    atoms.add(f"{name}|misplaced|{member}")
    return atoms


def _extract_declared_modules_exist(root):
    from scripts.organization.tests_layout_contract import module_home

    tests_root = root / "tests"
    atoms = set()
    for fname, group in module_home().items():
        if not (tests_root / group / fname).is_file():
            atoms.add(f"tests_module_home|missing|tests/{group}/{fname}")
    return atoms


def _extract_authority_axis(root):
    from scripts.organization.tests_layout_contract import (
        DESIGN_CONTRACT_GROUPS,
        TEST_GROUPS,
        design_contract_authority,
    )

    contracts_files = set(dict((g.name, g.modules) for g in TEST_GROUPS)["contracts"])
    authority = design_contract_authority()
    authority_files = set(authority)
    atoms = symmetric_atoms(
        "authority_axis", "uncovered", contracts_files, "stale", authority_files
    )
    seen = set()
    for mods in DESIGN_CONTRACT_GROUPS.values():
        for member in mods:
            if member in seen:
                atoms.add(f"authority_axis|duplicate|{member}")
            seen.add(member)
    tests_contracts = root / "tests" / "contracts"
    for member in authority_files:
        if not (tests_contracts / member).is_file():
            atoms.add(f"authority_axis|missing_file|{member}")
    return atoms


# The CLOSED seven-id map. Keys are the EXACT fully-qualified failing ids of the
# slice-0 seed; a mapped test's fingerprint is the sorted set these produce.
STRUCTURAL_EXTRACTORS = {
    f"{_SL_ID}::test_declared_homes_have_no_phantom_members": _extract_phantom,
    f"{_SL_ID}::test_every_src_module_has_a_declared_home": _extract_src_home,
    f"{_SL_ID}::test_every_test_file_has_a_declared_home": _extract_test_home,
    f"{_SL_ID}::test_guard_fires_on_a_forged_or_misplaced_file": _extract_guard,
    f"{_SL_ID}::test_placement_enforced_groups_live_in_their_subdir": _extract_placement,
    f"{_TL_ID}::test_declared_modules_exist": _extract_declared_modules_exist,
    f"{_TL_ID}::test_design_contracts_grouped_by_authority": _extract_authority_axis,
}
STRUCTURAL_EXTRACTOR_IDS = frozenset(STRUCTURAL_EXTRACTORS)


def structural_atoms(test_id, repo_root=None):
    """Sorted-set atomic ``category|side|member`` violations for a mapped
    structural ``test_id``, recomputed from the LIVE collections.

    Returns ``None`` for an unmapped id (an ordinary test keeps its terminal
    fingerprint). Raises :class:`ExtractorUnavailable` if the live collections
    cannot be read — the runner then keeps the terminal line, which is
    unledgered and reddens (§13.2 "no atom ⇒ the exception line reddens").
    """
    fn = STRUCTURAL_EXTRACTORS.get(test_id)
    if fn is None:
        return None
    root = Path(repo_root) if repo_root is not None else _discover_repo_root()
    try:
        return set(fn(root))
    except ExtractorUnavailable:
        raise
    except Exception as exc:  # unreadable layout data / unimportable contract
        raise ExtractorUnavailable(f"{test_id}: {exc!r}") from exc


# --------------------------------------------------------------------------- #
# Trusted runner — runs the pinned command, validates honesty, verifies
# INSEPARABLY against the git-loaded parent (§13.2). This is the binding
# entry point; the pure verifiers above are not the trust boundary alone.
# --------------------------------------------------------------------------- #

RunResult = namedtuple("RunResult", ("output", "returncode"))

_RAN_RE = re.compile(r"^Ran\s+(\d+)\s+tests?\b", re.M)
_STATUS_RE = re.compile(r"^(OK|FAILED)\b")
_VERBOSE_RE = re.compile(r"^\S+ \(([\w.]+)\) \.\.\. ")


def _command_modules(command):
    """The fully-qualified test modules named after ``python -m unittest`` in the
    pinned command string (flags and the env prefix dropped)."""
    tokens = shlex.split(command)
    try:
        idx = tokens.index("unittest")
    except ValueError:
        raise RatchetRunError("pinned command is not a 'python -m unittest' invocation")
    modules = [t for t in tokens[idx + 1:] if not t.startswith("-") and "." in t]
    if not modules:
        raise RatchetRunError("pinned command names no fully-qualified test modules")
    return modules


def _terminal_status(output):
    """The LAST ``OK`` / ``FAILED`` line, or ``None`` if the run never reported
    one (truncated / crashed / forged output)."""
    status = None
    for line in output.splitlines():
        match = _STATUS_RE.match(line)
        if match:
            status = match.group(1)
    return status


def _executed_modules(output, modules):
    """Named modules that produced at least one executed verbose test line."""
    seen = set()
    for line in output.splitlines():
        match = _VERBOSE_RE.match(line)
        if not match:
            continue
        class_path = match.group(1)
        for mod in modules:
            if class_path == mod or class_path.startswith(mod + "."):
                seen.add(mod)
    return seen


def _module_of_class(class_path):
    return class_path.rsplit(".", 1)[0] if "." in class_path else class_path


def _check_run(output, returncode, modules, observed_raw):
    """Assert the RUN itself is honest, returning ``(ran, status)``.

    Rejects: no ``Ran N`` summary; ``Ran 0`` (deleting tests / unmasking a
    zero-test module is not progress); no terminal status; a return code that
    disagrees with that status; a named module that was never DISCOVERED
    (neither executed a test nor is a declared loader/``setUpClass`` mask); and
    any observed identity that is not fully qualified under a named module.
    """
    ran_match = _RAN_RE.search(output)
    if not ran_match:
        raise RatchetRunError("no 'Ran N tests' summary — the run crashed or its output was truncated")
    ran = int(ran_match.group(1))
    if ran == 0:
        raise RatchetRunError("zero tests ran — deleting tests or unmasking to zero tests is a dishonest shrink")
    status = _terminal_status(output)
    if status is None:
        raise RatchetRunError("no terminal OK/FAILED status line — the run output is truncated or forged")

    problems = []
    if status == "OK" and returncode != 0:
        problems.append(f"terminal status OK but return code {returncode} (expected 0)")
    if status == "FAILED" and returncode == 0:
        problems.append("terminal status FAILED but return code 0 (expected nonzero)")

    executed = _executed_modules(output, modules)
    masked = {mod for mod, _fp in observed_raw["loader"]}
    masked |= {_module_of_class(cls) for cls, _fp in observed_raw["setupclass"]}
    undiscovered = [mod for mod in modules if mod not in executed and mod not in masked]
    if undiscovered:
        problems.append(f"named modules never discovered (zero tests and not masked): {sorted(undiscovered)}")

    named = set(modules)
    for tid, _fp in observed_raw["ordinary"]:
        class_path = tid.split("::", 1)[0]
        if not any(class_path == mod or class_path.startswith(mod + ".") for mod in named):
            problems.append(f"observed ordinary id not fully qualified under a named module: {tid!r}")
    for mod, _fp in observed_raw["loader"]:
        if mod not in named:
            problems.append(f"observed loader module is not a named fully-qualified module: {mod!r}")
    for cls, _fp in observed_raw["setupclass"]:
        if _module_of_class(cls) not in named:
            problems.append(f"observed setUpClass is not under a named module: {cls!r}")

    if problems:
        raise RatchetRunError("dishonest run; " + "; ".join(problems))
    return ran, status


def _apply_atomic_extractor(observed, atomic_extractor, repo_root):
    """Rewrite the seven structural ids' ordinary fingerprints to their atomic
    members; every other observation is passed through unchanged. A mapped id
    whose extractor yields no atom keeps its terminal line (which reddens)."""
    extract = atomic_extractor or (lambda tid: structural_atoms(tid, repo_root))
    ordinary = set()
    for tid, fp in observed["ordinary"]:
        if tid in STRUCTURAL_EXTRACTOR_IDS:
            try:
                atoms = extract(tid)
            except ExtractorUnavailable:
                atoms = None
            if atoms:
                for atom in atoms:
                    ordinary.add((tid, atom))
                continue
        ordinary.add((tid, fp))
    return {
        "ordinary": ordinary,
        "loader": set(observed["loader"]),
        "setupclass": set(observed["setupclass"]),
    }


def _default_subprocess_runner(command, repo_root):
    proc = subprocess.run(
        command, shell=True, cwd=str(repo_root), capture_output=True, text=True
    )
    return RunResult(output=(proc.stdout or "") + (proc.stderr or ""), returncode=proc.returncode)


def _default_git_show(base_ref, rel_path, repo_root):
    proc = subprocess.run(
        ["git", "show", f"{base_ref}:{rel_path}"],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RatchetRunError(f"git show {base_ref}:{rel_path} failed: {(proc.stderr or '').strip()}")
    return proc.stdout


def run_and_verify(baseline_path, *, base_ref, subprocess_runner=None, git_show=None, atomic_extractor=None):
    """The binding ratchet check: RUN, validate honesty, verify INSEPARABLY.

    1. Load the candidate ledger and RUN its pinned ``command`` as a subprocess
       in the worktree root (``baseline_path``'s ``…/contracts/`` parent).
    2. Validate the run with :func:`_check_run` (``Ran N>0``, terminal status,
       return-code agreement, module discovery, fully-qualified identities).
    3. Derive ``observed`` from the REAL output, rewriting the seven structural
       ids to atomic members via the extractor.
    4. Load the PARENT ledger via ``git show <base_ref>:<rel path>`` — the caller
       supplies only ``base_ref``, never a parent object, so a candidate cannot
       be its own parent except by literally being unchanged at ``base_ref``.
    5. Invoke :func:`verify_observation_projection`,
       :func:`verify_subset_of_parent` and :func:`verify_frozen_structure`
       INSEPARABLY — any raise aborts the whole verification.

    Returns ``{ran, status, returncode, modules, ledger_change, frozen}`` on a
    clean pass. ``subprocess_runner`` / ``git_show`` / ``atomic_extractor`` are
    injectable for hermetic tests; the defaults are the real subprocess, real
    ``git show`` and the live :func:`structural_atoms`.
    """
    baseline_path = Path(baseline_path).resolve()
    repo_root = baseline_path.parent.parent
    rel_path = baseline_path.relative_to(repo_root).as_posix()

    candidate = load_ledger(baseline_path)
    command = candidate.get("command")
    if not isinstance(command, str) or not command.strip():
        raise RatchetRunError("candidate ledger has no pinned 'command' to run")
    modules = _command_modules(command)

    run = subprocess_runner(command) if subprocess_runner else _default_subprocess_runner(command, repo_root)
    output, returncode = run.output, run.returncode

    observed_raw = observe_from_unittest_output(output)
    ran, status = _check_run(output, returncode, modules, observed_raw)
    observed = _apply_atomic_extractor(observed_raw, atomic_extractor, repo_root)

    parent_text = git_show(base_ref, rel_path) if git_show else _default_git_show(base_ref, rel_path, repo_root)
    parent = _loads_no_dupes(parent_text)

    # INSEPARABLE — all three, or the verification fails.
    verify_observation_projection(candidate, observed)
    ledger_change = verify_subset_of_parent(candidate, parent)
    frozen = verify_frozen_structure(candidate, parent)

    return {
        "ran": ran,
        "status": status,
        "returncode": returncode,
        "modules": modules,
        "ledger_change": ledger_change,
        "frozen": frozen,
    }
