<div align="center">

[![My Skills](https://skillicons.dev/icons?i=python,java,cpp,rust,ruby,html&theme=dark&perline=6)](https://skillicons.dev)
[![My Tools](https://skillicons.dev/icons?i=spring,docker,git,github,githubactions,linux,bash,vscode&theme=dark&perline=8)](https://skillicons.dev)

</div>

---

<div align="center">

<img src="metrics.general.svg" width="49%" alt="GitHub Stats" />
<img src="https://streak-stats.demolab.com/?user={{ username }}&theme=tokyonight&hide_border=true&background=1a1b27&ring=7AA2F7&fire=ff9e64&currStreakNum=7AA2F7&sideNums=7AA2F7&currStreakLabel=7AA2F7&sideLabels=a9b1d6&dates=565f89" width="49%" alt="GitHub Streak" />

</div>

---

### By The Numbers

<div align="center">

<img src="assets/badges.svg" alt="Profile Badges" />

</div>

---

### Builder Scorecard

<div align="center">

<img src="assets/builder_scorecard.svg" alt="Builder Scorecard" />

</div>

---

### Contribution Calendar

<div align="center">

<img src="assets/contribution_calendar.svg" alt="Contribution Calendar" />

</div>

---

### Current Focus

<div align="center">

<img src="assets/now_next_shipped.svg" alt="Current Focus" />

</div>

---

### Currently Working On

<div align="center">

<img src="assets/currently_working.svg" alt="Currently Working On" />

</div>

---

### Language Breakdown

<div align="center">

<img src="assets/lang_breakdown.svg" alt="Language Breakdown" />

</div>

---

### When I Code

<div align="center">

<img src="assets/activity_heatmap.svg" alt="Activity Heatmap" />

</div>

---

### Flagship Projects

<div align="center">

<img src="assets/repo_spotlight.svg" alt="Featured Projects" />

</div>

---

### Raw Data Snapshot (Python Pull)

<div align="center">

<img src="assets/raw_snapshot.svg" alt="Raw Data Snapshot" />

</div>

### Deep Dive Data

- [Open the full dashboard]({{ dashboard_url }})
- [Open raw profile snapshot JSON](site/data/profile_snapshot.json)
- Generated by `python scripts/profile_cli.py generate-profile --validate` from the GitHub API.
- Full project matrix, delivery feed, language distribution, and recently created repositories are preserved in the dashboard + JSON.
