<div align="center">

[![My Skills](https://skillicons.dev/icons?i=python,java,cpp,rust,ruby,html&theme=dark&perline=6)](https://skillicons.dev)
[![My Tools](https://skillicons.dev/icons?i=spring,docker,git,github,githubactions,linux,bash,vscode&theme=dark&perline=8)](https://skillicons.dev)

</div>

---

<div align="center">

<img src="metrics.general.svg?v={{ cache_bust }}" width="100%" alt="GitHub Stats" />

</div>

---

<div align="center">

<img src="assets/streak_summary.svg?v={{ cache_bust }}" width="100%" alt="Streak Summary" />

</div>

---

<div align="center">

<img src="assets/badges.svg?v={{ cache_bust }}" width="100%" alt="Profile Badges" />

</div>

---

<div align="center">

<img src="assets/builder_scorecard.svg?v={{ cache_bust }}" width="100%" alt="Builder Scorecard" />

</div>

---

<div align="center">

<img src="assets/engineering_cadence.svg?v={{ cache_bust }}" width="100%" alt="Engineering Cadence" />

</div>

---

<div align="center">

<img src="assets/contribution_calendar.svg?v={{ cache_bust }}" width="100%" alt="Contribution Calendar" />

</div>

---

<div align="center">

<img src="assets/now_next_shipped.svg?v={{ cache_bust }}" width="100%" alt="Current Focus" />

</div>

---

<div align="center">

<img src="assets/currently_working.svg?v={{ cache_bust }}" width="100%" alt="Currently Working On" />

</div>

---

<div align="center">

<img src="assets/lang_breakdown.svg?v={{ cache_bust }}" width="100%" alt="Language Breakdown" />

</div>

---

<div align="center">

<img src="assets/activity_heatmap.svg?v={{ cache_bust }}" width="100%" alt="Activity Heatmap" />

</div>

---

<div align="center">

<img src="assets/repo_spotlight.svg?v={{ cache_bust }}" width="100%" alt="Flagship Projects" />

</div>

---

<div align="center">

<img src="assets/raw_snapshot.svg?v={{ cache_bust }}" width="100%" alt="Raw Data Snapshot" />

</div>

### Deep Dive Data

- [Open the full dashboard]({{ dashboard_url }})
- [Open raw profile snapshot JSON](site/data/profile_snapshot.json)
- Generated by `python scripts/profile_cli.py generate-profile --validate` from the GitHub API.
- Full project matrix, delivery feed, language distribution, and recently created repositories are preserved in the dashboard + JSON.
